# Generated by Django 5.2.6 on 2025-10-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='apartment_number',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.TextField(blank=True),
        ),
    ]
