# Generated by Django 5.2.6 on 2025-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_alter_voter_apartment_number_alter_voter_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
