# Generated by Django 5.2.6 on 2025-10-30 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_alter_voter_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
    ]
