# Generated by Django 5.2.6 on 2025-12-04 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_show_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('W', 'Watching'), ('F', 'Finished')], default='W', max_length=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='project.show')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watches', to='project.viewer')),
            ],
            options={
                'unique_together': {('viewer', 'show')},
            },
        ),
    ]
