# Generated by Django 5.2.6 on 2025-12-07 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='viewer', to='project.viewer'),
        ),
    ]
