# Generated by Django 5.2.6 on 2025-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_season_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='status',
            field=models.CharField(choices=[('W', 'Watching'), ('F', 'Finished'), ('P', 'Want to Watch')], default='P', max_length=1),
        ),
    ]
